### ISSUE TITLE
Kan ban Project Info

### ISSUE THREAD

**Issue by AJ193** [AJ193/React-Group-Project#21]
Dear Reviewer:

The link to the Project is  https://github.com/AJ193/React-Group-Project/

In this project we are three coding partners
@AJ193 is the student A
@yemidada is the student B
@kamranasif506 is the Student C

**Comment by iambenkis** [comment]
# STATUS: APPROVED :green_circle: :clap: 

## Hi @AJ193 , @yemidada , and @kamranasif506  🙋‍♂️, 
Your kanbanboard is setup correctly!  There is nothing else to say other than... Great job 👏 

HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />

Cheers and Happy coding!👏👏👏
